### ISSUE TITLE
get convergence for procobserr 1-day model

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#112]
So far, Jags has converged more quickly/easily than Stan for what seem to be very similar models (both just the 1-day versions for now). Why? What can be done to get Stan to converge more readily?
https://github.com/aappling-usgs/streamMetabolizer/blob/d7ddd738151ae3c938a509c5a12f59399ec026f0/inst/models/bayes/nopool_procobserr_pairmeans.stan
https://github.com/aappling-usgs/streamMetabolizer/blob/d7ddd738151ae3c938a509c5a12f59399ec026f0/inst/models/bayes/nopool_procobserr_pairmeans.jags

**Comment by aappling-usgs** [comment]
I haven't been very systematic about this yet, but constraining phi sure seems to help. Here's a run from just now (code not yet committed) with phi capped at 0.01. The code pasted here goes within the test-metab_bayes.R file, with vfrench1day as defined there.

```r
> model_specs <- specs_bayes_stan_nopool_procobserr(n_cores=4, burnin_steps=2000, num_saved_steps=1000, err_proc_phi_max=0.01)
> model_specs$model_path <- system.file(paste0("models/bayes/", model_specs$model_file), package="streamMetabolizer") # usually added in metab_bayes
> data_list <- streamMetabolizer:::prepdata_bayes(
+ data=vfrench1day, data_daily=NULL, local_date="2012-08-24", model_specs=model_specs, priors=FALSE)
> system.time({
+     mcmc_out <- do.call(streamMetabolizer:::mcmc_bayes, c(
+       list(data_list=data_list, keep_mcmc=TRUE),
+       model_specs[c('bayes_software','model_path','params_out','n_chains','n_cores','burnin_steps','num_saved_steps','thin_steps','verbose')]))
+   })
MCMC: requesting 4 chains on 4 of 8 available cores

   user  system elapsed 
   0.64    0.79   45.80 
```

![image](https://cloud.githubusercontent.com/assets/12039957/10550669/2cfd0dfc-7416-11e5-996b-f586da622616.png)

**Comment by aappling-usgs** [comment]
For comparison, here's the exact same code except with err_proc_phi allowed to be anywhere between 0 and 1:
```r
> model_specs <- specs_bayes_stan_nopool_procobserr(n_cores=4, burnin_steps=2000, num_saved_steps=1000, err_proc_phi_max=1)
> model_specs$model_path <- system.file(paste0("models/bayes/", model_specs$model_file), package="streamMetabolizer") # usually added in metab_bayes
> data_list <- streamMetabolizer:::prepdata_bayes(
+ data=vfrench1day, data_daily=NULL, local_date="2012-08-24", model_specs=model_specs, priors=FALSE)
> system.time({
+     mcmc_out <- do.call(streamMetabolizer:::mcmc_bayes, c(
+       list(data_list=data_list, keep_mcmc=TRUE),
+       model_specs[c('bayes_software','model_path','params_out','n_chains','n_cores','burnin_steps','num_saved_steps','thin_steps','verbose')]))
+   })
MCMC: requesting 4 chains on 4 of 8 available cores

   user  system elapsed 
   0.75    0.78  260.71 
Warning messages:
1: There were 28 divergent transitions after warmup. Increasing adapt_delta may help. 
2: There were 55 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth. 
3: Examine the pairs() plot to diagnose sampling problems
 
> traceplot(mcmc_out$stanfit[[1]])
```
![image](https://cloud.githubusercontent.com/assets/12039957/10550810/19f2fc3e-7417-11e5-8197-a4a6aa397773.png)

**Comment by aappling-usgs** [comment]
the above 2 comments come from code as committed in https://github.com/aappling-usgs/streamMetabolizer/commit/c17ed7cc1fc2734770e2cd050a6937ea6a43810b

**Comment by robohall** [comment]
Chain 1 is getting stuck on phi = 1.  Need more warmup, but that avoids the more central question of assigning a phi to the process error.  Fixing at 0.01 is saying that proc error is iid.  Assigning phi = say proc error is random walk.  They have big consequences for metabolism, but it is a little disconcerting that the modeli cannot pick it.  What data are these?  Fake?  And do they have a autocorrelated process error?

Bob
On Oct 16, 2015, at 1:03 PM, Alison Appling <notifications@github.com<mailto:notifications@github.com>> wrote:


For comparison, here's the exact same code except with err_proc_phi allowed to be anywhere between 0 and 1:

> model_specs <- specs_bayes_stan_nopool_procobserr(n_cores=4, burnin_steps=2000, num_saved_steps=1000, err_proc_phi_max=1)
> model_specs$model_path <- system.file(paste0("models/bayes/", model_specs$model_file), package="streamMetabolizer") # usually added in metab_bayes
> data_list <- streamMetabolizer:::prepdata_bayes(
+ data=vfrench1day, data_daily=NULL, local_date="2012-08-24", model_specs=model_specs, priors=FALSE)
> system.time({
+     mcmc_out <- do.call(streamMetabolizer:::mcmc_bayes, c(
+       list(data_list=data_list, keep_mcmc=TRUE),
+       model_specs[c('bayes_software','model_path','params_out','n_chains','n_cores','burnin_steps','num_saved_steps','thin_steps','verbose')]))
+   })
MCMC: requesting 4 chains on 4 of 8 available cores

   user  system elapsed
   0.75    0.78  260.71
Warning messages:
1: There were 28 divergent transitions after warmup. Increasing adapt_delta may help.
2: There were 55 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth.
3: Examine the pairs() plot to diagnose sampling problems

> traceplot(mcmc_out$stanfit[[1]])

[image]<https://cloud.githubusercontent.com/assets/12039957/10550810/19f2fc3e-7417-11e5-8197-a4a6aa397773.png>

**Comment by aappling-usgs** [comment]
Yep to all that. I don't really have a problem believing that process error is iid, though I know we've talked a lot about it and want to explore the possibility that process error is itself autocorrelated. I'm using the french creek data - see https://github.com/aappling-usgs/streamMetabolizer/blob/c17ed7cc1fc2734770e2cd050a6937ea6a43810b/tests/testthat/test-metab_bayes.R

**Comment by aappling-usgs** [comment]
we're working through all this. using stan and specific stan code implementations helps. using priors helps. avoiding pc models helps. we'll get there.
