### ISSUE TITLE
replace lookup_usgs_elevation

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#121]
The USGS NED API service seems to have disappeared. Find its new location or find a substitute.

I think it has moved into USGS's The National Map. See nationalmap.gov and http://services.nationalmap.gov/arcgis/sdk/rest/index.html#/Getting_started/02ss00000048000000/ ...you'd think http://nationalmap.gov/epqs/ would be the place (the old endpoint was http://ned.usgs.gov/epqs/pqs.php), but the new one still gives 'Error: 503 Service unavailable!'

**Comment by jread-usgs** [comment]
http://ndgishub.nd.gov/ArcGIS/rest/services/All_Elevation/MapServer ?

**Comment by aappling-usgs** [comment]
Is there a national version? That one seems to be ND focused

**Comment by jread-usgs** [comment]
yeah, just realized that, so I deleted it.

**Comment by jread-usgs** [comment]
~~http://ndgishub.nd.gov/ArcGIS/rest/services/All_Elevation/MapServer~~ for the record

**Comment by aappling-usgs** [comment]
thanks for looking, anyway. the best I've found so far is the reference at http://nationalmap.gov/3DEP/3dep_prodserv.html, which says that nationalmap.gov/epqs hosts a Point Query Service

**Comment by aappling-usgs** [comment]
I've convinced myself that they intend the service to exist, but that it may not be working right now. So I've emailed tnm_help@usgs.gov to ask about it.

**Comment by aappling-usgs** [comment]
Got a prompt and useful email back from Calvin at tnm_help@usgs.gov this morning. I suspect the service was temporarily down when I tried 2 days ago. Switch to the new endpoint was pushed to my develop branch just now - works fine.
