### ISSUE TITLE
unify naming conventions for imported LMetab functions

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/streamMetabolizer#17]

**Comment by jread-usgs** [comment]
schmidt and do_deficit are taken care of w/ recent PRs. k600.2.kgas and day2doy remain

**Comment by aappling-usgs** [comment]
i think the calc_xxx scheme looks good

**Comment by aappling-usgs** [comment]
Open to changes later, but we seem to have settled pretty solidly on calc_xxx and convert_x_to_y

**Comment by jread-usgs** [comment]
Looks great to me.
