### ISSUE TITLE
Package "unitted" as a dependency

### ISSUE THREAD

**Issue by padpadpadpad** [USGS-R/streamMetabolizer#181]
When attempting to install this package using `devtools::install_github('lawinslow/streamMetabolizer')` R gives an error as `unitted` is specified as a dependency in the DESCRIPTION file but is not actually an R package as far as I can tell.

**Comment by aappling-usgs** [comment]
Thanks for your interest in the package! `streamMetabolizer` is increasingly functional and/but still in development. We welcome bold, flexible, resilient new users who can help us make the package better. If that's you, please see our README, especially the [Installation section](https://github.com/USGS-R/streamMetabolizer#installation).

**Comment by padpadpadpad** [comment]
Hi everyone. Firstly I think this package is awesome. Secondly I now realise unitted is in itself an R package currently only available on GitHub (much like yourselves) so you need to install that before installing streamMetabolizer.

For anyone downloading the package for the first time that would be useful info. :)

**Comment by aappling-usgs** [comment]
Yes, and thanks for adding your discovery to the issue so others can benefit. Somewhat more stable versions of both `unitted` and `streamMetabolizer` are also available on the USGS-R repository at "http://owi.usgs.gov/R"
