### ISSUE TITLE
Should we use match.args on inputs?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/streamMetabolizer#21]
handy function, or too sloppy?

**Comment by aappling-usgs** [comment]
i think it's useful and un-sloppy (tidy, even) when you're using it to make sure the user is selecting one of a set of acceptable arguments. otherwise, probably not needed

**Comment by jread-usgs** [comment]
ok, I am :+1: on this too.

**Comment by jread-usgs** [comment]
Closing this issue. we will follow this pattern when appropriate.
