### ISSUE TITLE
Add Bob to this project

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#24]
looks like  @jread-usgs or another owner has to do this

**Comment by aappling-usgs** [comment]
probably want to tell him about Not Watching option (for shout-outs only)

**Comment by jread-usgs** [comment]
@robohall - you should get an invite to be part of this collaboration. If the email clatter from our progress gets to be too much, you can change from being a "watcher" to "not watching", which will only result in emails when you are part of conversations or mentioned w/ @robohall
![image](https://cloud.githubusercontent.com/assets/2349007/7310535/4dc397a2-e9f3-11e4-8e8f-6b88b571a419.png)
