### ISSUE TITLE
Input tibble data?

### ISSUE THREAD

**Issue by berdaniera** [USGS-R/streamMetabolizer#274]
FYI, when running a metabolism fit with input data as a `tibble`, `mm_validate_data()` throws an error: `expecting 'solar.time' to be of class 'POSIXct'` (I assume since it looks at a tibble as a list or something). We were stymied until we converted the input data to a traditional `data.frame`, and it all worked. 

Do you want to allow users to input tibbles?

**Comment by aappling-usgs** [comment]
Thanks for the idea. I'll put this on the long-term to-do list.

**Comment by aappling-usgs** [comment]
@berdaniera - I finally fixed this, I think. If you try it, please let me know if you find any residual issues with using tibbles.
