### ISSUE TITLE
assess runtimes

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#280]
# Priorities

The most important thing is to have acceptably quick runtimes for `b_Kb_oipi_plrckm.stan` models. Early results indicated that we'll see the best oipi runtime with the present implementation (DO loop with DO_mod_partial to capture process error). We're comfortable with our decisions to use, and implementations of, b, stan, plrc, and km. That leaves Kb and the shape of the K distributions -- we like Kb in theory and so far also in practice, but it would help to answer questions 1, 2, and 3 below to make sure we've reached good performance. We are also generally interested in having fast models across the board, which brings overlapping and additional questions.

# Questions

1. Are models faster using normally or lognormally distributed K600_daily and/or hierarchical K600 parameters?
2. Do hierarchical models scale linearly or otherwise as the number of days increases?
3. How much does the data resolution matter to runtime?
4. Are pi models with the new implementation (using a DO loop) slower than pi models with the original implementation (using a dDOdt loop)?

**Comment by aappling-usgs** [comment]
# Results

# 3. How much does the data resolution matter to runtime?

> sapply(mms, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 74.09                  69.87                  69.21                  71.07 
> dat <- mutate(data_metab('10', res='15'), discharge=seq(5,15,length.out=n()))
> mms15 <- lapply(setNames(nm=stanfiles), function(sf) {
+     message(sf)
+     metab(specs(sf), if(mm_parse_name(sf)$pool_K600 %in% c('linear','binned')) dat else select(dat, -discharge))
+   })
b_Kb_oi_tr_plrckm.stan
b_Kl_oi_tr_plrckm.stan
b_Kn_oi_tr_plrckm.stan
b_np_oi_tr_plrckm.stan
> sapply(mms15, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 57.16                  55.55                  58.06                  57.55 
> dat <- mutate(data_metab('10', res='30'), discharge=seq(5,15,length.out=n()))
> mms30 <- lapply(setNames(nm=stanfiles), function(sf) {
+     message(sf)
+     metab(specs(sf), if(mm_parse_name(sf)$pool_K600 %in% c('linear','binned')) dat else select(dat, -discharge))
+   })
b_Kb_oi_tr_plrckm.stan
b_Kl_oi_tr_plrckm.stan
b_Kn_oi_tr_plrckm.stan
b_np_oi_tr_plrckm.stan
> sapply(mms30, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 31.89                  31.82                  29.91                  31.51

**Comment by aappling-usgs** [comment]
## Conclusions:

Things that matter to runtime:
* Data length (I'm actually just assuming this right now, but soon see Q2 for the evidence).
* Data resolution. Twice the resolution means twice the time. See Q1 and Q3.
* Data complexity. Some datasets are harder than others. See Q1.
* Lognormal vs normal distributions of K, maybe, but Q1 suggests that if anything, we've sped up the models by switching to lognormals. Woot!
* Error assumptions. The oi models run about 10 times faster than the oipi models; see Q1 and #264 . pi models are almost as slow as oipi models; see Q4.

**Comment by robohall** [comment]
oi should be much faster than oipi models because we are solving for the true unknown O2 at each timestep where
DO.dat  ~ N(DO.true, sig.obs)
DO.true.t ~  N( f(DO.true.t-1, GPP, ER,K), sig.proc)

**Comment by aappling-usgs** [comment]
Agreed - we expect that `oi` will be faster than `oipi` because it's way less complex. We can hope to keep the gap between them narrow, though. 

In my SFS talk in May I had an 8-month example where `oi` took 2 hours, `oipi` before optimization took 27 hours (13 times slower than `oi`), and `oipi` after optimization took 3.5 hours (1.8 times slower than `oi`). 

I believe I've now implemented that optimization throughout streamMetabolizer, so I had been hoping for runtimes a little closer to one another. But maybe the new `oi` models are somehow faster than the old ones, and/or maybe we'll see more comparable runtimes between `oi` and `oipi` for other datasets. Let's keep an eye on that.

**Comment by robohall** [comment]
Running b_Kn_oi_tr_plrckm.stan and it too is dragging as slowly as the oipi that just took me 3500 sec for 3000 iterations on a 3 day model.  That is weird, because stan should rip through a oi model since it is not estimating the state (true but unknown DO) at each time step. This is good news/bad news.  Good news is that estimating the state in a state-space model is not slowing down the run time.  Bad news is that something else is.

**Comment by robohall** [comment]
Correct that last comment.  600 seconds versus 3500 for a oi vs oipi model.  Output nearly matched that of the mle model showing minimal pooling, which I expect given only 3 days and the model's tendency to not want to pool with oi models.

I am going to find a slightly longer and easier dataset to deal with for further tests.  But good news that bayes and oi ~ mle

**Comment by aappling-usgs** [comment]
somewhat faster as of https://github.com/USGS-R/streamMetabolizer/commit/dd800225ba820736f85ed635da8d4ef9cce6d58a, especially for pooling models:
```r
> library(streamMetabolizer)
> library(testthat)
> library(dplyr)
> 
> # create a list of all models to run
> opts <- expand.grid(
     type='bayes',
     pool_K600=c('none','normal','linear','binned'),
     err_obs_iid=T,#c(TRUE, FALSE),
     err_proc_acor=F,#c(FALSE, TRUE),
     err_proc_iid=F,#c(FALSE, TRUE),
     ode_method='trapezoid',#c('trapezoid','euler'),
     GPP_fun='linlight',
     ER_fun='constant',
     deficit_src='DO_mod',#c('DO_mod','DO_obs'),
     engine='stan',
     check_validity=FALSE,
     stringsAsFactors=FALSE)
> stanfiles <- opts %>% rowwise %>% do(data_frame(model_name=do.call(mm_name, .))) %>% unlist(use.names=FALSE) %>% sort %>%
 {.[!grepl('__', .)]}
> dat <- mutate(data_metab('10', res='15'), discharge=seq(5,15,length.out=n()))
> mms15 <- lapply(setNames(nm=stanfiles), function(sf) {
          message(sf)
          metab(specs(sf), if(mm_parse_name(sf)$pool_K600 %in% c('linear','binned')) dat else select(dat, -discharge))
        })
b_Kb_oi_tr_plrckm.stan
b_Kl_oi_tr_plrckm.stan
b_Kn_oi_tr_plrckm.stan
b_np_oi_tr_plrckm.stan
> sapply(mms15, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 44.07                  51.21                  50.19                  66.16 
```
Or if we omit err_obs_iid and err_proc_iid from the list of parameters to monitor:
```r
> mms15 <- lapply(setNames(nm=stanfiles), function(sf) {
          message(sf)
          metab(revise(specs(sf), params_out=setdiff(params_out, c('err_obs_iid','err_proc_iid'))), if(mm_parse_name(sf)$pool_K600 %in% c('linear','binned')) dat else select(dat, -discharge))
        })
> sapply(mms15, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 41.97                  50.62                  44.69                  59.48
```

Compare to the earlier result from https://github.com/USGS-R/streamMetabolizer/issues/280#issuecomment-259231245:
```r
> sapply(mms15, function(mm) get_fitting_time(mm)[['elapsed']])
b_Kb_oi_tr_plrckm.stan b_Kl_oi_tr_plrckm.stan b_Kn_oi_tr_plrckm.stan b_np_oi_tr_plrckm.stan 
                 57.16                  55.55                  58.06                  57.55 
```
