### ISSUE TITLE
limiting dependencies?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#35]
How careful do we want to be about additional dependencies? For example, in PR #34 I just added lubridate to aid in a single function, but I could probably remove that dependency if needed. Not sure yet whether lubridate will be useful in functions we'll be writing later.

**Comment by lawinslow** [comment]
Dependencies are cheap IMHO. I haven't found a great reason to limit them yet.

**Comment by jread-usgs** [comment]
Yeah, but some packages are heavy and can create some odd errors when others try to install. We are working with dates enough to have `lubridate` make a lot of sense as a dep. Other things that are just being used for a small part of a function should be considered before loading on a new dep. I guess luke and I slightly disagree on this point.

**Comment by jread-usgs** [comment]
Aren't you the same person who was lamenting all the deps on `devtools` when you use it on condor?

**Comment by lawinslow** [comment]
Condor is my burden to bear. Even I don't take it into consideration when I work on my packages. 

But yeah, I would avoid dependencies that don't work or install cleanly on all platforms.
