### ISSUE TITLE
MLE model works with example data but bayes model does not because "can't find metabolism parameters GPP.daily, ER.daily, K600.daily"

### ISSUE THREAD

**Issue by Kelsman28** [USGS-R/streamMetabolizer#359]
Hello, I installed both the most stable and in-development versions of the package and was able to run the MLE model but not the Bayes with the French Creek data.  

When trying to fit the Bayes model using code from the "Getting Started with stream metabolizer page" I got the following:

bayes_name <- mm_name(
type='bayes', pool_K600='none', 
err_obs_iid=TRUE, err_proc_acor=FALSE, err_proc_iid=TRUE, 
ode_method='trapezoid')

bayes_specs <- specs(bayes_name)
bayes_specs
Model specifications:
  model_name               b_np_oipi_tr_plrckm.stan                                                                          
  engine                   stan                                                                                              
  split_dates              FALSE                                                                                             
  keep_mcmcs               TRUE                                                                                              
  keep_mcmc_data           TRUE                                                                                              
  day_start                4                                                                                                 
  day_end                  28                                                                                                
  day_tests                full_day, even_timesteps, complete_data, pos_discharge                                            
  required_timestep        NA                                                                                                
  GPP_daily_mu             3.1                                                                                               
  GPP_daily_lower          -Inf                                                                                              
  GPP_daily_sigma          6                                                                                                 
  ER_daily_mu              -7.1                                                                                              
  ER_daily_upper           Inf                                                                                               
  ER_daily_sigma           7.1                                                                                               
  K600_daily_meanlog       2.484906649788                                                                                    
  K600_daily_sdlog         1                                                                                                 
  err_obs_iid_sigma_scale  0.03                                                                                              
  err_proc_iid_sigma_scale 5                                                                                                 
  params_in                GPP_daily_mu, GPP_daily_lower, GPP_daily_sigma, ER_daily_mu, ER_daily_upper, ER_daily_sigma, K6...
  params_out               GPP, ER, GPP_daily, ER_daily, K600_daily, err_obs_iid_sigma, err_obs_iid, err_proc_iid_sigma, e...
  n_chains                 4                                                                                                 
  n_cores                  4                                                                                                 
  burnin_steps             500                                                                                               
  saved_steps              500                                                                                               
  thin_steps               1                                                                                                 
  verbose                  FALSE                  
                                                                           
bayes_fit <- metab(bayes_specs, data=dat)
Timing stopped at: 1.76 0.03 2.18
Warning message:
In metab_fun(specs = specs, data = data, data_daily = data_daily,  :
  Modeling failed
  Warnings:
    running command 'C:/PROGRA~1/R/R-34~1.1/bin/x64/R CMD SHLIB file23cc1b9c2ef8.cpp 2> file23cc1b9c2ef8.cpp.err.txt' had status 1  Errors:
    Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file23cc1b9c2ef8.dll" WIN=64 TCLBIN=64 OBJECTS="file23cc1b9c2ef8.o"' had status 127

select(get_params(bayes_fit), warnings, errors)
Error in get_params.metab_model(bayes_fit) : 
  can't find metabolism parameters GPP.daily, ER.daily, K600.daily

This is what I installed

install.packages(
  c("LakeMetabolizer","unitted","dplyr","lazyeval","lubridate","magrittr",
    "tidyr","chron","dygraphs","ggplot2","RCurl","rstan","XML","xts"),
  repos=c("https://owi.usgs.gov/R","https://cran.rstudio.com"))

devtools::install_github("USGS-R/streamMetabolizer", ref="develop")

devtools::find_rtools() 

library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate) ## this masks baseR date
library(streamMetabolizer)

I have not specifically installed stan on my computer but rtools should take care of that right?

Will try running nighttime regression now.

Thank you,

Julie Kelso

**Comment by aappling-usgs** [comment]
I see you closed the issue, @Kelsman28 - were you able to resolve the problem?
