### ISSUE TITLE
Unable to grab example data frames

### ISSUE THREAD

**Issue by dmcostello** [USGS-R/streamMetabolizer#383]
---

### Brief problem description
The data_metab() function does function properly on a new install of streamMetabolizer and dplyr packages. There seems to be an issue with the unitted package that is used to create the data frame.

### What you saw on your computer
When running the following code
```r
library(streamMetabolizer)
dat <- data_metab(num_days='3', res='15', attach.units=TRUE)
```
I get this error:
Error in as.data.frame.default(list(station = new("unitted_character",  : 
  cannot coerce class ‘structure("unitted_data.frame", package = "unitted")’ to a data.frame

### Session information
─ Session info ───────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-03-24                  

─ Packages ───────────────────────────────────────────────────────────────────────────────
 package           * version  date       lib source        
 assertthat          0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports           1.1.5    2019-10-02 [1] CRAN (R 3.6.0)
 callr               3.4.2    2020-02-12 [1] CRAN (R 3.6.0)
 cli                 2.0.1    2020-01-08 [1] CRAN (R 3.6.0)
 crayon              1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 desc                1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 deSolve             1.27.1   2020-01-02 [1] CRAN (R 3.6.0)
 devtools            2.2.2    2020-02-17 [1] CRAN (R 3.6.0)
 digest              0.6.25   2020-02-23 [1] CRAN (R 3.6.0)
 dplyr             * 0.8.4    2020-01-31 [1] CRAN (R 3.6.0)
 ellipsis            0.3.0    2019-09-20 [1] CRAN (R 3.6.0)
 fansi               0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 fs                  1.3.1    2019-05-06 [1] CRAN (R 3.6.0)
 glue                1.3.1    2019-03-12 [1] CRAN (R 3.6.0)
 knitr               1.28     2020-02-06 [1] CRAN (R 3.6.0)
 LakeMetabolizer     1.5.0    2016-06-23 [1] CRAN (R 3.6.0)
 lazyeval            0.2.2    2019-03-15 [1] CRAN (R 3.6.0)
 lifecycle           0.1.0    2019-08-01 [1] CRAN (R 3.6.0)
 lubridate           1.7.4    2018-04-11 [1] CRAN (R 3.6.0)
 magrittr            1.5      2014-11-22 [1] CRAN (R 3.6.0)
 memoise             1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 pillar              1.4.3    2019-12-20 [1] CRAN (R 3.6.0)
 pkgbuild            1.0.6    2019-10-09 [1] CRAN (R 3.6.0)
 pkgconfig           2.0.3    2019-09-22 [1] CRAN (R 3.6.0)
 pkgload             1.0.2    2018-10-29 [1] CRAN (R 3.6.0)
 plyr                1.8.5    2019-12-10 [1] CRAN (R 3.6.0)
 prettyunits         1.1.1    2020-01-24 [1] CRAN (R 3.6.0)
 processx            3.4.2    2020-02-09 [1] CRAN (R 3.6.0)
 ps                  1.3.2    2020-02-13 [1] CRAN (R 3.6.0)
 purrr               0.3.3    2019-10-18 [1] CRAN (R 3.6.0)
 R6                  2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 Rcpp                1.0.3    2019-11-08 [1] CRAN (R 3.6.0)
 remotes             2.1.1    2020-02-15 [1] CRAN (R 3.6.0)
 rLakeAnalyzer       1.11.4.1 2019-06-09 [1] CRAN (R 3.6.0)
 rlang               0.4.4    2020-01-28 [1] CRAN (R 3.6.0)
 rprojroot           1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi          0.11     2020-02-07 [1] CRAN (R 3.6.0)
 sessioninfo         1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 streamMetabolizer * 0.10.9   2020-03-03 [1] local         
 stringi             1.4.6    2020-02-17 [1] CRAN (R 3.6.0)
 stringr             1.4.0    2019-02-10 [1] CRAN (R 3.6.0)
 testthat            2.3.1    2019-12-01 [1] CRAN (R 3.6.0)
 tibble              2.1.3    2019-06-06 [1] CRAN (R 3.6.0)
 tidyr               1.0.2    2020-01-24 [1] CRAN (R 3.6.0)
 tidyselect          1.0.0    2020-01-27 [1] CRAN (R 3.6.0)
 unitted           * 0.2.9    2019-05-01 [1] local         
 usethis             1.5.1    2019-07-04 [1] CRAN (R 3.6.0)
 vctrs               0.2.3    2020-02-20 [1] CRAN (R 3.6.0)
 withr               2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
 xfun                0.12     2020-01-13 [1] CRAN (R 3.6.0)
 yaml                2.2.1    2020-02-01 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by aappling-usgs** [comment]
Thanks for reporting this. The newest version available on GitHub has a bugfix for this. I've updated the documentation to recommend installation from GitHub (instead of GRAN, which may be deprecated soon). You can get the latest with:
```r
remotes::install_github("USGS-R/streamMetabolizer")
```
