### ISSUE TITLE
Calculate light data for entire 'solar.time' column instead doing one by one?

### ISSUE THREAD

**Issue by nuwanma1986** [USGS-R/streamMetabolizer#394]
Hi, 
I need to use the following codes to calculate light for the entire "solar.time" column instead on calculating for one by one?

solar.time <- lubridate::force_tz(as.POSIXct('2016-09-27 12:00'), 'UTC')
calc_light(solar.time, 40, -120)
library(unitted)
calc_light(u(solar.time), u(40, 'degN'), u(-120, 'degE'), u(2315, 'umol m^-2 s^-1'), 
  attach.units=TRUE)

Here is my data:
dput(datanew)
structure(list(solar.time = structure(c(1547505126.48, 1547506026.48, 
1547506926.48, 1547507826.48, 1547508726.48, 1547509626.48, 1547510526.48, 
1547511426.48, 1547512326.48, 1547513226.48, 1547514126.48, 1547515026.48, 
1547515926.48, 1547516826.48, 1547517726.48, 1547518626.48, 1547519526.48, 
1547520426.48), tzone = "UTC", class = c("POSIXct", "POSIXt")), 
    Temp = c(16.947, 16.862, 16.752, 16.735, 16.65, 16.608, 16.523, 
    16.455, 16.412, 16.361, 16.293, 16.25, 16.267, 16.216, 16.148, 
    16.114, 16.054, 16.046), DO = c(8.45, 8.429, 8.425, 8.379, 
    8.38, 8.358, 8.354, 8.344, 8.334, 8.323, 8.329, 8.314, 8.291, 
    8.29, 8.298, 8.29, 8.296, 8.289)), row.names = c(NA, -18L
), class = "data.frame")

**Comment by robohall** [comment]
You are in luck:  sM can generate light given a location.  Below is a function call to generate light for the Arikaree River from work I did last week.

calc_light(arik_df$solar.time2, latitude=39.758, longitude=-102.4471, max.PAR =2326, attach.units = F)

You will need a daily estimate of mean depth for the reach, this is much more important than where you derive light data

After you have estimate daily metabolism, and want to use light to predict daily variation in GPP, you will need actual light and satellite products work well fr that e..g NLDAS.

Bob Hall



On Aug 2, 2020, at 3:47 PM, nuwanma1986 <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,
I have continuous DO and temperature datasets, which I want to calculate stream GPP, ER, and metabolism. However, I don't have light intensity data, therefore I am wondering is it possible to use 'streamMetabolizer' package without light intensity data?

**Comment by nuwanma1986** [comment]
Thanks Bob
