### ISSUE TITLE
Issues with "streamMetabolizer" data format?

### ISSUE THREAD

**Issue by nuwanma1986** [USGS-R/streamMetabolizer#395]
Hi Alison and Bob,

I have a dataset as follows, which I want to calculate stream metabolism using the package 'streamMetabolizer'. However, I am struggling with the attached appropriate units. I would be grateful if you could provide assistance with this? 

solar.time DO.obs      DO.sat depth temp.water      light
2   2019-01-14 13:26:06    9.9 9.991925717 0.516       15.4 2008.47170
3   2019-01-14 13:36:06     10 9.996001599 0.516       15.6 1973.59621
4   2019-01-14 13:46:06     10 9.961151509 0.516       15.8 1936.01443
5   2019-01-14 13:56:06     10 9.916699722 0.516       15.9 1895.79787
6   2019-01-14 14:06:06     10 9.917683229 0.516         16 1853.02303
7   2019-01-14 14:16:06    9.9 9.817532725 0.516         16 1807.77131

 Many Thanks,
Nuwan

**Comment by aappling-usgs** [comment]
Hi Nuwan,

Your data.frame above starts with row 2, and earlier you shared that the first row contains the units. In proper **unitted** format, the units would not be in a row of their own; they would be stored separately like the column names.

You can find some documentation for the **unitted** package at https://github.com/appling/unitted/blob/master/README.md and in the function help docs (e.g., `?unitted::u`, `?unitted::v`, but it'll likely be easier for you to remove the units labels altogether (once you've determined that your numeric data have the magnitudes that match the units you intend). Units are optional in **streamMetabolizer**. You can leave them out of your .csv file and use `attach.units=FALSE` when you call `calc_light`.

Alison

**Comment by nuwanma1986** [comment]
Thanks Alison.
