### ISSUE TITLE
package is not available (for R version 3.3.2)

### ISSUE THREAD

**Issue by mlbrooks** [USGS-R/streamMetabolizer#416]
### Brief problem description

Believe this is an entirely new problem on the forum. When I try to run the package using the following 
 
install.packages("streamMetabolizer", dependencies=TRUE, 
                   repos=c("https://owi.usgs.gov/R","https://cran.rstudio.com"))

### What you saw on your computer
I receive the message: 

Warning in install.packages :
  package ‘streamMetabolizer’ is not available (for R version 3.3.2)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES'

I received this same message using the most recent 4.2.1 version of R.

A colleague also tried to install the package and received the same message. Both of us were able to download Lake Metabolizer.

Any suggestions are most appreciated. 

mlbrooks

**Comment by mlbrooks** [comment]
Bob Hall was good enough to point out that I likely needed to install the "remote' package, which I did from the cran mirror. 

Following that step, I followed his advice below: 
First install the unitted dependency:
>remotes::install_github('appling/unitted')

You can then install the most cutting edge version of streamMetabolizer with this command:
>remotes::install_github("USGS-R/streamMetabolizer")

Thanks, Bob.

**Comment by sasindug** [comment]
I also have the same problem.  I installed "remote' package using remotes::install_github('appling/unitted') and the tried to install streamMetabolizer using the following code.
remotes::install_github("USGS-R/streamMetabolizer")

I keep getting following error
ERROR: dependency 'LakeMetabolizer' is not available for package 'streamMetabolizer'
* removing 'C:/Users/sasin/AppData/Local/R/win-library/4.2/streamMetabolizer'
Warning messages:
1: package ‘LakeMetabolizer’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘C:/Users/sasin/AppData/Local/Temp/RtmpQVMMtp/file2804513054a0/streamMetabolizer_0.12.0.tar.gz’ had non-zero exit status

Please let me know what to do
Thanks

**Comment by mlbrooks** [comment]
Greetings,

Last week, I continued my efforts to load streamMetabolizer on a second laptop. Since the instructions on USGS-R/streamMetabolizer produced the error message described below, I spent some time searching for a means to download LakeMetabolizer. As a result, I found that it has been removed from the cran mirror as of 10/3/2022.

Before that date, I downloaded the LakeMetabolizer package on the one laptop on which I can run streamMetabolizer. Thus, my conclusion is that it would be helpful if the LakeMetabolizer package were made available again despite it's apparent flaws. Seems essential.

Best regards,
Marj
Dr. Marjorie L Brooks
Biogeochemistry and Aquatic Ecology
1125 Lincoln Dr, MC 6501
Carbondale, IL 62901

Office: Life Science II Building, Room 317
Laboratory: Life Science II Building, Room 311
Cell: 307-399-0576
Tel: 618-453-7639

**Comment by sasindug** [comment]
> 

Thanks for letting me know.

**Comment by nmarzolf91** [comment]
[LakeMetabolizer ](https://github.com/GLEON/LakeMetabolizer)is available via `devtools::install_github('GLEON/LakeMetabolizer')` 

and should be run in addition to: 
```
remotes::install_github('appling/unitted')
remotes::install_github("USGS-R/streamMetabolizer")
```

**Comment by jordansread** [comment]
Oh wow, I didn't realize LakeMetabolizer was removed from CRAN. I created an issue. https://github.com/GLEON/LakeMetabolizer/issues/147

In the meantime, the solution from @sasindug should work. I'd slightly revise that to 
```r
remotes::install_github('GLEON/LakeMetabolizer')
remotes::install_github('appling/unitted')
remotes::install_github('USGS-R/streamMetabolizer')
```
So you can do it all with `remotes`

**Comment by mlbrooks** [comment]
Thank you.

Dr. Marjorie L Brooks, Associate Professor
Biogeochemistry and Aquatic Ecology
1125 Lincoln Dr, MC 6501
Carbondale, IL 62901

Office: Life Science II Building, Room 317
Laboratory: Life Science II Building, Room 311
Cell: 307-399-0576
Tel: 618-453-7639

**Comment by jzwart** [comment]
LakeMetabolizer is back on CRAN https://cran.r-project.org/web/packages/LakeMetabolizer/index.html

**Comment by mlbrooks** [comment]
Good to hear!

Dr. Marjorie L Brooks
Biogeochemistry and Aquatic Ecology
1125 Lincoln Dr, MC 6501
Carbondale, IL 62901

Office: Life Science II Building, Room 317
Laboratory: Life Science II Building, Room 311
Cell: 307-399-0576
Tel: 618-453-7639

**Comment by jordansread** [comment]
Thanks @jzwart !

**Comment by aappling-usgs** [comment]
Yay for community debugging! Thanks, everyone.

**Comment by mlbrooks** [comment]
Thanks, Alison.

Dr. Marjorie L Brooks
Biogeochemistry and Aquatic Ecology
1125 Lincoln Dr, MC 6501
Carbondale, IL 62901

Office: Life Science II Building, Room 317
Laboratory: Life Science II Building, Room 311
Cell: 307-399-0576
Tel: 618-453-7639
