### ISSUE TITLE
Research LakeMetabolizer utility functions, pull them in 

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/streamMetabolizer#5]
`@importFrom ...` and create lightweight wrappers if appropriate (if only useful as a private function, do not expose to user).

**Comment by jread-usgs** [comment]
Starting this with a few obvious ones:
**getSchmidt:** https://github.com/GLEON/LakeMetabolizer/blob/master/R/getSchmidt.R
**k600 converter:** https://github.com/GLEON/LakeMetabolizer/blob/master/R/k600.2.kGAS.R
**DOsat:** https://github.com/GLEON/LakeMetabolizer/blob/master/R/o2.at.sat.R
**par2sw & sw2par:** https://github.com/GLEON/LakeMetabolizer/blob/master/R/par.to.sw.R
**sunrise/set and isday/night:** https://github.com/GLEON/LakeMetabolizer/blob/master/R/sun.rise.set.R

(not sure how we want to name them...)

**Comment by aappling-usgs** [comment]
About halfway through this right now. Not sure about naming, either - going to start by keeping the same names, but maybe a series of functions named convert_abc, convert_dce, etc. would make sense
