### ISSUE TITLE
build vignettes into package

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/streamMetabolizer#68]

**Comment by aappling-usgs** [comment]
one vignette is currently available & up to date as of 2/1/16: https://github.com/USGS-R/streamMetabolizer/blob/develop/vignettes/model_types.Rmd

**Comment by aappling-usgs** [comment]
a good one would be an example of how to prepare your data - import to df, rename columns, compute solar.time, light, DO.sat, check against mm_data() formals

**Comment by aappling-usgs** [comment]
also show how to convert from chron or character times to POSIXct times

**Comment by aappling-usgs** [comment]
ready for vignette demonstrating metab() options & how to identify proper defaults (moving from #142)
- mm_valid_names
- mm_name
- specs
- metab

**Comment by aappling-usgs** [comment]
see http://usgs-r.github.io/streamMetabolizer/getstarted.html. there will be modifications and additions later, of course, but closing this issue because this vignette is a good start.
