### ISSUE TITLE
Model to simulate data

### ISSUE THREAD

**Issue by Arroita** [USGS-R/streamMetabolizer#73]
This might not make sense, but question: I agree that simulated data should be created including the process error, but can the model used to create the data influence the results of the comparison between this model and another (the one without process error). I mean, could someone say results obtained with model A are better because data were created with model A? This is why the objective of 
confirming we’ve made the right assumption about the presence of process error in real data was included.

Need to figure out what phi should be to create simulated data.

**Comment by robohall** [comment]
We need to simulate data using all combinations of error,  i.e, obs, proc, autocorrelated proc,  and then use all of those three combinations to try to extract the parameters.  Several times to test bias and precision.  

Start with phi= 0.8

**Comment by aappling-usgs** [comment]
As of PR #96, metab_sim() models accept 

Argument | Description
----- | -----
`err.obs.sigma` | The sd of observation error, or 0 for no observation error. Observation errors are those applied to DO.mod after generating the full time series of modeled values.
`err.obs.phi` | The autocorrelation coefficient of the observation errors, or 0 for uncorrelated errors.
`err.proc.sigma` | The sd of process error, or 0 for no process error. Process errors are applied at each time step, and therefore propagate into the next timestep.
`err.proc.phi` | The autocorrelation coefficient of the process errors, or 0 for uncorrelated errors.
`sim.seed` | NA to specify that each call to predict_DO should generate new values, or an integer, as in the seed argument to set.seed, specifying the seed to set before every execution of predict_DO
```

**Comment by aappling-usgs** [comment]
Moving issue to USGS-CIDA/metab_tests repo now that the streamMetabolizer implementation is complete.
